### ISSUE TITLE
Problem with utf-8 encoding

### ISSUE THREAD

**Issue by rhadamants** [synspawacza/nier_automata_localization#1]
I'm having trouble with utf-8 encoding in accented letters. The letters appear with two characters within the game.
The tool is not accepting ANSI files.

**Comment by synspawacza** [comment]
Added fix. I hope this solves the problem.

**Comment by rhadamants** [comment]
Insert is ok with last commit.
But extraction give this on spanish and another language but only extract issue using latin1.
`or key, value in kv.items():
        result += (escape_nonascii(key + "=" + value, keep_non_ascii) + "\n").encode(
            "latin1", "backslashreplace"`

> Iniciar comprobacixF3n del sistema

**Comment by rhadamants** [comment]
Use utf-16 is fine to extract. Japonese, spanish all ok.

But insert with files extracted give error: 

> building global_d595bcd1_scp
Traceback (most recent call last):
  File "./tools/put_strings.py", line 59, in <module>
    insert_strings_to_file(args.input, args.strings, args.output, args.lang)
  File "./tools/put_strings.py", line 39, in insert_strings_to_file
    mapping = properties.parse_properties(properties_file)
  File "/mnt/d/lixo/nier_automata_localization-master/tools/format/properties.py", line 19, in parse_properties
    for line in text_reader.readlines():
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by rhadamants** [comment]
Leave utf-8 to extract and latin1 to insert is fine.
But need --keep-non-ascii
