### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by indrasundanese** [synspawacza/nier_automata_localization#10]
I'm on Ubuntu 22.04
After done translating on omegaT, i create Target
yes i check all file already there...

But after run `./build_localization.sh`
in terminal show many error like this "No such file or directory" i check every single file in target
every file/properties exis
![Screenshot from 2022-11-18 05-03-05](https://user-images.githubusercontent.com/58340595/202569734-208ebf7b-cff5-40b5-a9eb-1d2e2dd09b3b.png)

![Screenshot from 2022-11-18 05-02-52](https://user-images.githubusercontent.com/58340595/202569765-b4a8c489-8aae-42b6-bab5-dc886feb151f.png)

**Comment by synspawacza** [comment]
Hello,

What is your target language in OmegaT? You might need to change `TLANG="_pl" # language suffix` in `build_localization.sh` to whatever is suffix for your `target/*.properties` files.

**Comment by indrasundanese** [comment]
i don't get it, i just open omegat project after prepare.sh, and start translate on omegat without look what language is this, as far i know i translate english to my local language indonesian.


what should i change this too? i don't get it?
TLANG="_pl"

**Comment by indrasundanese** [comment]
NVM i got it, but after i copy all folder in "output" to gamedir\data
in game all string/text is missing?

in the end output on terminal there still error "No such file or directory"
look like its only dds/dtt/font i forget to take the log

**Comment by indrasundanese** [comment]
Here the log.

[log.zip](https://github.com/synspawacza/nier_automata_localization/files/10045278/log.zip)

**Comment by indrasundanese** [comment]
Here the log.

[log.zip](https://github.com/synspawacza/nier_automata_localization/files/10045278/log.zip)

**Comment by synspawacza** [comment]
If you didn't add new font characters and run `build_fonts.sh`, you should copy fonts to assembly:
`cp -r unpacked/font assembly/`

**Comment by indrasundanese** [comment]
I do, and i begin the step from the beginning (just for make sure everything is right)
Here the log, from the beginning (only error in this log)

[Log.zip](https://github.com/synspawacza/nier_automata_localization/files/10045521/Log.zip)

Result:

![NieR Automata Screenshot 2022 11 18 - 23 10 09 46](https://user-images.githubusercontent.com/58340595/202821093-3f3bd857-6886-4fb9-88fa-d596276efe4e.png)

**Comment by indrasundanese** [comment]
Also i can't see "font folder" in output after running build_localization.sh
i already: cp -r unpacked/font assembly/
