### ISSUE TITLE
I get error at prepare.sh

### ISSUE THREAD

**Issue by ImanIranNejad** [synspawacza/nier_automata_localization#11]
hi i just started to use your code. but i stuck at the very begining . i just cant get the prepare.sh working . im using win 11 and i installed wsl and installed python3 with pillow library but i cant run this script
![Screenshot 2023-10-23 232703](https://github.com/synspawacza/nier_automata_localization/assets/119811160/4be83019-2560-4bd3-b51a-2ccd43f03a6a)

and here is what i extracted from the game. i tried to move the folders from /data/data002.cpk_unpacked to /data/ folder but i still have issues
![Screenshot 2023-10-23 232722](https://github.com/synspawacza/nier_automata_localization/assets/119811160/991e7530-9c13-48dc-824b-427b8d30cfae)

**Comment by synspawacza** [comment]
Hello,

I find it a bit weird. Everywhere in the repo I am using `#!/usr/bin/python3` shebang and unix endlines. `/usr/bin/python^M bad interpreter` error would appear when using  `#!/usr/bin/python` shebang and windows endlines. Moreover, `prepare.sh` is bash script, so at least first `echo` would run, before running any python script.

Can you show, what first lines of `prepare.sh` looks like, i.e. run `head prepare.sh`?

**Comment by ImanIranNejad** [comment]
I actually cant believe you answered me xD . Sorry but i shifted to Debian for this tool to work. i don't have access on windows anymore but seems like prepare.sh works fine on linux.
I unpacked files successfully and right now i'm getting confuse about font characters you mention to add . i don't have anything in font folder of the project.
I know its a different subject but i would like to translate this Lovely game to Persian . I need a little help with this basic thing you said in readme <3

**Comment by ImanIranNejad** [comment]
actully let me close this and open another one
