### ISSUE TITLE
Use Omegat

### ISSUE THREAD

**Issue by rhadamants** [synspawacza/nier_automata_localization#2]
What did you use for targeting?
project/omegat/segmentation.conf.

And is this text file in omegat just for me to know the order of the files or does it have any use in the Omegat project?

**Comment by synspawacza** [comment]
I just used _Java(TM) Resource Bundles_ file filter. It takes each key-value pair in *.properties file as a single segment and adds key as a comment (useful to provide context). There are some giant segments, but for most parts it is ok. For *.txt files I used default segmentation.

File files_order.txt is used by OmegaT. It is more or less UI -> main quests -> side quests -> DLC order. It is not perfect, text from different routes are a bit mixed up, but better than default order.

**Comment by rhadamants** [comment]
I can not segment the "=".
I thought you were able to segment using "=".
