### ISSUE TITLE
Problem with kerning

### ISSUE THREAD

**Issue by Xerron1998** [synspawacza/nier_automata_localization#5]
I'm using this tool to translate the game into Chinese.
The only problem is words overlap each other.
How can i fix the kerning problem?
![001](https://user-images.githubusercontent.com/46190439/126866212-95fa4b4b-f0f7-4800-84b6-49cab01f9978.png)
![002](https://user-images.githubusercontent.com/46190439/126866217-90f3096e-b2d2-4b49-9580-9e799a9f57c5.png)

**Comment by synspawacza** [comment]
I haven't seen such issue before. Try changing `"kerning"` setting in `fonts/fonts.json` to `null` and see if that helps.

BTW, while reverse engineering files, I noticed what looks like unused Korean and Chinese translations in `bin` files. I updated `get_strings.py`.

**Comment by Xerron1998** [comment]
This problem is only in UI files, everything is fine with subtitles, mission introductions, etc

**Comment by Xerron1998** [comment]
I tried changing "kerning" setting in fonts/fonts.json to null , then build localization, but the ui words still overlap each other.

**Comment by Xerron1998** [comment]
Is there a way to set the font kerning manually？

**Comment by synspawacza** [comment]
Can you provide `messloading.properties` and `messtitle.properties` files? I'll try to recreate the issue.

**Comment by Xerron1998** [comment]
[translated properties files.zip](https://github.com/synspawacza/nier_automata_localization/files/6881770/translated.properties.files.zip)

**Comment by Xerron1998** [comment]
Ah, I see.
It seems that the size of the font PNG files i created are inconsistent with files from game
I modified the PNG size and solved the problem
![无标题](https://user-images.githubusercontent.com/46190439/127077860-3d1a798d-c0aa-45e4-8c9d-6e8e62893019.png)
